### ISSUE TITLE
functional requirement

### ISSUE THREAD

**Issue by wokula** [ferrumgate/secure.client#42]
"policies/Authorization"

Currently, only policies for a single service can be added,

Can we add functionality to enable multiple services to correspond to multiple users or user groups for policy making。

This allows for a unified set of access policies for a department.

**Comment by ferrumgate** [comment]
This is a good idea, Thanks for offering, I added to roadmap list.

**Comment by ferrumgate** [comment]
I pushed the task to dev team, they rejected because services can be different, some of them Tcp/Udp, some of them DNS,
(we are planning to implement SSH, RDP and HTTP services), every service type has different capabilities. if Service is DNS then
DNS filtering rules can be applied, and more.

**Comment by wokula** [comment]
Your development team's thinking is too rigid, and development is only considered from the perspective of business services. If you consider the direction of user and organizational structure access rules. There wouldn't be such a problem

For special DNS services, they can be filtered out. This is not a problem.

There is no problem with small-scale products in your current product structure. If there are a large number of users and multiple organizational departments, it is impossible to add access rules based on business service access rules one by one.

If users or organizations need to access 30 business services, do they need to implement 30 access rules. What if the requirement is 100 business services?

**Comment by ferrumgate** [comment]
You are absolutely right, Big business services will have problem about so much rules. We will add this feature.
