### ISSUE TITLE
OPEN LDAP Error

### ISSUE THREAD

**Issue by joksa97** [ferrumgate/secure.client#49]
I found that when configuring the Auth model with OpenLDAP like when I create the Active Directory, the Redis base stops, and the application needs to restart. Also, is it not possible to connect users using OpenLDAP?

**Comment by ferrumgate** [comment]
let's check for more details.

- please activate OpenLDAP authentication and disable ActiveDirectory
- please activate ActiveDirectory authenticaton and disable OpenLDAP
