### ISSUE TITLE
DNS on Windows doesnt work

### ISSUE THREAD

**Issue by davidlomanto** [ferrumgate/secure.client#51]
When you install on windows, we have to create all the relations of DNS and IP(the IP'S that was created for the services by ferrumgate) to make that work at hosts. 
In Linux, works perfectly.

**Comment by ferrumgate** [comment]
@davidlomanto  we know that windows does not have any problem, 
let's check it  together, 
after connected to your ferrumgate instance
please check if your client logs has "make dns router"
then
please type on windows cmd
`reg query HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters /v SearchList`
please check if your network name is in result. 
`ipconfig /all`
please check if your ferrumgate dns service ip is in list,
Or you can send outputs to support@ferrumgate.com, we will be happy help to solve it
