### ISSUE TITLE
OSX agent doesn't launch

### ISSUE THREAD

**Issue by jmessenger51** [ferrumgate/secure.client#56]
I have an ARM based mac and downloaded (ferrumgate_1.9.0_mac_arm64.dmg):

It failed to install, but followed: https://ferrumgate.com/docs/clients/ and ran :
` xattr -rc /Applications/FerrumGate.app`
this failed as -r wasn't a valid flag
re-ran with:
` xattr -c /Applications/FerrumGate.app`
and it installed. When I clicked on the application in OSX I see:

![image](https://github.com/ferrumgate/secure.client/assets/59372273/8b6752c6-eb2d-445a-996d-c6d682bb1634)

but there isn't an ability to configure the application, it appears to load in the background. I see Ferrumgate in my dock and processes start:
<img width="289" alt="image" src="https://github.com/ferrumgate/secure.client/assets/59372273/3c2110eb-a957-4a0d-a9ea-3c5123282ffd">

But nothing in the tray and no other windows.

OSX version / model are:
<img width="376" alt="image" src="https://github.com/ferrumgate/secure.client/assets/59372273/f1c935da-b2cf-4d82-9eb6-c78fc029927e">

**Comment by hamzakilic** [comment]
Probably it is about icon resolution problem, what is screen resolution

**Comment by jmessenger51** [comment]
I have (2) displays
     1st is 1728x1117
     2nd is 1920x1080

**Comment by hamzakilic** [comment]
this is about icons problem, I will check it

**Comment by jmessenger51** [comment]
Which PR resolved the screen resolution issue?

**Comment by ferrumgate** [comment]
we trying to put release 1.10.0 version. it will be fixed in this version. please test it when it is released
